### ISSUE TITLE
impossible to use Lt.matrix() when using a list of vectors in ga.Ga.lt() (brombo/galgebra#10)

### ISSUE THREAD

**Issue by eric-wieser** [pygae/galgebra#105]
@chaowenGUO commented on Mar 18, 2016

<blockquote>
          <p>import ga,sympy<br>
base=ga.Ga('a b',g=[1,1],coords=sympy.symbols('x,y',real=True))<br>
a,b=base.mv()<br>
A=base.lt([a+b,a-b])<br>
print A<br>
print A.matrix()</p>
<p>output is:<br>
Lt(a) = a + b<br>
Lt(b) = a - b<br>
Traceback (most recent call last):<br>
File "test.py", line 6, in <br>
print A.matrix()<br>
File "/home/ken/galgebra-master/galgebra/lt.py", line 476, in matrix<br>
self.mat = Dictionary_to_Matrix(self.lt_dict, self.Ga) * self.Ga.g<br>
File "/home/ken/galgebra-master/galgebra/lt.py", line 102, in Dictionary_to_Matrix<br>
(coefs,bases) = metric.linear_expand(dict_rep[e_row])<br>
File "/home/ken/galgebra-master/galgebra/metric.py", line 62, in linear_expand<br>
if expr.is_commutative:<br>
AttributeError: 'Mv' object has no attribute 'is_commutative'</p>
<p>that means it construct linear transformation correctly, but can not convert to sympy matrix</p>
      </blockquote>

---

From http://webcache.googleusercontent.com/search?q=cache:https://github.com/brombo/galgebra/issues/10

**Comment by eric-wieser** [comment]
Still fails on master:
```
In [42]: from galgebra import ga; import sympy
    ...: base=ga.Ga('a b',g=[1,1],coords=sympy.symbols('x,y',real=True))
    ...: a,b=base.mv()
    ...: A=base.lt([a+b,a-b])
    ...: print(A)
    ...: print(A.matrix())
Lt(a) = a + b
Lt(b) = a - b
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-42-8e268445ec66> in <module>
      4 A=base.lt([a+b,a-b])
      5 print(A)
----> 6 print(A.matrix())

~\Repos\ga\galgebra\galgebra\lt.py in matrix(self)
    489                 return(Matrix(mat_rep).transpose())
    490                 """
--> 491                 self.mat = Dictionary_to_Matrix(self.lt_dict, self.Ga) * self.Ga.g
    492                 return self.mat
    493

~\Repos\ga\galgebra\galgebra\lt.py in Dictionary_to_Matrix(dict_rep, ga)
    108
    109         if e_row in basis:  # If not in basis row all zeros
--> 110             (coefs,bases) = metric.linear_expand(dict_rep[e_row])
    111             for (coef,base) in zip(coefs,bases):
    112                 index = ga.basis.index(base)

~\Repos\ga\galgebra\galgebra\metric.py in linear_expand(expr, mode)
     37         args = expr.args
     38     else:
---> 39         if expr.is_commutative:
     40             return ([expr], [S(1)])
     41         else:

AttributeError: 'Mv' object has no attribute 'is_commutative'
```

**Comment by utensil** [comment]
Reading the code of `linear_expand`, it seems to assume that it's working with a plain SymPy object, probably a type-checking guard like `isinstance(expr, mv.Mv)` and convert using `mv.obj` will fix this bug.

**Comment by utensil** [comment]
No, `metric` should not depend on `mv` so the fix should be ensuring the `expr` to be a plain SymPy.

**Comment by utensil** [comment]
It's using `.lt` in a way different from the test case in `examples/Terminal/lt_test.py`, we need to take care of both cases: when it's created using plain SymPy objects or `Mv`s.
