### ISSUE TITLE
exp of non-simple bivectors fails (brombo/galgebra#29)

### ISSUE THREAD

**Issue by eric-wieser** [pygae/galgebra#114]
@arsenovic commented on Sep 26, 2016

<blockquote>
          <p>if  i try to make a rotor from a non-simple bivector in G4, i get an error.</p>
<pre><code>from sympy import symbols
from galgebra import ga
from galgebra.mv  import exp
`

g4g = '1 0 0 0, 0 1 0 0, 0 0 1 0, 0 0 0 1' 
g4 = ga.Ga('e_1 e_2 e_3 e_4',g=g4g)     

e1,e2,e3,e4 = g4.mv() 

e12 = e1^e2
e34 = e3^e4

J = e12+e34

theta = symbols('theta')
exp(theta*J)

</code></pre>
<p>gives</p>
<pre><code>--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
&lt;ipython-input-7-e569c8166ee9&gt; in &lt;module&gt;()
     14 
     15 theta = symbols('theta')
---&gt; 16 exp(theta*J)

/home/alex/code/galgebra/galgebra/mv.pyc in exp(A, hint)
   2554 def exp(A,hint='-'):
   2555     if isinstance(A,Mv):
-&gt; 2556         return A.exp(hint)
   2557     else:
   2558         return sympy_exp(A)

/home/alex/code/galgebra/galgebra/mv.pyc in exp(self, hint)
   1165                     return tmp
   1166         else:
-&gt; 1167             raise ValueError('"' + str(self) + '**2" is not a scalar in exp.')
   1168 
   1169     def set_coef(self, igrade, ibase, value):

ValueError: "theta*e_1^e_2 + theta*e_3^e_4**2" is not a scalar in exp.
</code></pre>
<p>fyi</p>
<pre><code>J**2 = −2+2e1∧e2∧e3∧e4
</code></pre>
      </blockquote>

@brombo commented on Sep 26, 2016

<blockquote>
          <p>J_J is a scalar plus a blade.  My J.exp() only works if J_J is a scalar.</p>
<p>J_J = -2 + 2_e_1^e_2^e_3^e_4</p>
<p>Also always use</p>
<p>theta = symbols('theta',real=True)</p>
<p>sympy assumes that symbols are complex numbers.</p>
      </blockquote>

@arsenovic commented on Sep 26, 2016

<blockquote>
          <p>ok. not sure if it helps, but rkern defined it this way,</p>
<p><a href="https://github.com/arsenovic/clifford/blob/master/clifford/__init__.py#L800-L828">https://github.com/arsenovic/clifford/blob/master/clifford/__init__.py#L800-L828</a></p>
      </blockquote>

@brombo commented on Sep 26, 2016

<blockquote>
          <p>rkern's method fine for numerical. Cannot know how many terms to take<br>
for symbolic expansion.</p>
      </blockquote>

---

From http://webcache.googleusercontent.com/search?q=cache:https://github.com/brombo/galgebra/issues/29

**Comment by utensil** [comment]
Same nature as #116
