### ISSUE TITLE
raise a multivector to a symbolic power (brombo/galgebra#32)

### ISSUE THREAD

**Issue by eric-wieser** [pygae/galgebra#116]
@arsenovic commented on Dec 22, 2016

<blockquote>
          <p>not sure if this makes sense, but would it be possible to handle symbols in the Multivector.<strong>pow</strong>() function?</p>
      </blockquote>

@ brombo commented on Dec 22, 2016

<blockquote>
</div>I would not know how to do it.</div>
      </blockquote>

---

From http://webcache.googleusercontent.com/search?q=cache:https://github.com/brombo/galgebra/issues/32

**Comment by utensil** [comment]
It's not possible in current basis-based implementation. Raising the basis to a symbolic and unknown power would completely mess things up, the result can't have a basis-baed representation. I would love the same thing and can implement it if GAlgebra is lazy and based on rewrite rules in a coordinate-free manner so further manipulation regarding the symbolic power can be done.

Close this as this is not a useful use case and impossible to implement in the near future.
