### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by FreddyBaudine** [pygae/galgebra#12]
Hi everybody,

I tried using galgebra in pygae but the following code,  viz., 
----------------------------------------
from sympy import symbols, sin, cos, pi
from ga import Ga
from printer import Forma,
Format(Fmode = True, Dmode = True)
coords = (r, th, phi) = symbols('r, theta, phi', real =  True)
sp3d = Ga('e_r e_th e_ph',g=[1, r**2, r**2*sin(th)**2], coords = coords, norm = True) 
--------------------------------------------------------------------------------------
lead to the following error
---------------------------------------------------------------------------
ValueError
Traceback (most recent call last)
<ipython-input-1-aa02a2b2e6ee> in <module>()
         1 from sympy import symbols, sin, cos, pi
----> 2 from ga import Ga
         3 from printer import Format
         4 Format(Fmode = True, Dmode = True)
         5 
C:\Documents and Settings\freddy baudine\Desktop\CliffordAlgebraPython\galgebra-master\galgebra\ga.py in <module>()
        10 #from sympy.core.compatibility import combinations
        11 from itertools import combinations
---> 12 from . import printer
        13 from . import metric
        14 from . import mv

ValueError: Attempted relative import in non-package
-----------------------------------------------------------

This piece of code did not give any error in the past
Many thanks in advance for any help.
Kind regards,
Freddy Baudine

**Comment by FreddyBaudine** [comment]
Dear all,
I am awfully sorry for the above bold font in my message.  I haven't got the slightest idea as to how this layout came about. Everything looked ok when I first wrote it.  Could be due to my copying the code in question.
Kind regards,
Freddy Baudine

**Comment by FreddyBaudine** [comment]
Sorry for the trouble, I made a silly mistake !
FB

**Comment by hugohadfield** [comment]
No problem Freddy, glad you have sorted out your issue!
