### ISSUE TITLE
Visualizing multivectors (brombo/galgebra#4)

### ISSUE THREAD

**Issue by eric-wieser** [pygae/galgebra#125]
Only available as a google snippet:

@meuns on 11 Feb 2016:

> Hello, I really like the book [1] and the simpy package you wrote. Are you aware of any python package extending your work for visualizing (e.g. plotting) the multi-vectors (not the equations) ?
>
> Best regards. Sylvain Meunier.
> [1] http://www2.montgomerycollege.edu/departments/planet/planet/Numerical_Relativity/bookGA.pdf

**Comment by utensil** [comment]
I'll label this and close. This nice feature won't be implemented in the near future and possibly out of the scope of GAlgebra. Possible approaches are integration with `pyganja` or `Grassmann.jl` at GAlgebra.jl level.
