### ISSUE TITLE
Move Pdop, Sdop and Dop out of mv.py

### ISSUE THREAD

**Issue by eric-wieser** [pygae/galgebra#133]
This probably make more sense in their own `dop.py`.

This might cause pain for @abrombo's printing work, so perhaps shouldn't be done until after that is resolved.

**Comment by utensil** [comment]
I concur, both that it should be done and the timing.

**Comment by eric-wieser** [comment]
Based on [this diff](https://github.com/pygae/galgebra/pull/62/files#diff-c8f426c9e23498c21dba55df60d9c12e), it doesn't look like this would actually be intrusive at all.

**Comment by eric-wieser** [comment]
Done in #137, we can always choose to delay merging

**Comment by eric-wieser** [comment]
Let's consider this done. `Dop` has been left in `mv.py` because it knows about multivectors.
