### ISSUE TITLE
Dop.blade_rep doesn't do anything

### ISSUE THREAD

**Issue by eric-wieser** [pygae/galgebra#147]
Note the lack of return statement or state modification

https://github.com/pygae/galgebra/blob/7995365bde093c1cec9b3f8523d346e67a46a28c/galgebra/mv.py#L2098-L2106

Also [an LGTM error](https://lgtm.com/projects/g/pygae/galgebra?mode=tree&ruleFocus=3960096) on line 2102

> For loop variable 'term' is not used in the loop body.

**Comment by utensil** [comment]
It seems to be intending to modify the state.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eric-wieser** [comment]
Does this seem reasonable?
```python
def blade_rep(self):
    return Dop([(coef.blade_rep(), pdiff) for coef, pdiff in self.terms)], cmpflg=self.cmpflg, ga=self.Ga)
```

**Comment by utensil** [comment]
Seem reasonable and consistent with the intention.

**Comment by eric-wieser** [comment]
Alternatively, we could just remove it - we can already spell that operation
```
some_dop = ga.grad
some_dop_base = some_dop.simpify(Mv.base_rep)
some_dop_blade = some_dop_base .simpify(Mv.base_rep)
assert some_dop_blade == some_dop_base 
```
