### ISSUE TITLE
Sympy 1.3 ill-calculates both the Laplacian and the d'Alembertian when applied to scalar and vector fields

### ISSUE THREAD

**Issue by FreddyBaudine** [pygae/galgebra#150]
Dear all,

I have come across a phenomenon that looks like an issue.
Making use of Simpy 1.3, the Laplacian of a scalar or a vector  field is ill calculated in that the second order derivative with respect to the variable x does not show up. 

The same mishap occurs with the Minkoswky metric, you end up with a d’Alambertian (c = 1) containing only three terms instead of four.

This phenomenon does not occur with earlier versions of Sympy, viz., versions 1.0, 1.1 and 1.2.

As the  experiment shows, the computation in spherical coordinates evinces no problem.

In addition to the above I was not able to reproduce the result obtained in Listing 3.4 of Section 3.9  Differential Operators, pp 69-70 of the GAlgebra book published on October 8, 2016.
The following ValueError is returned at some point:
```
Traceback (most recent call last):
  File "DotOperator_Simpy1.x.py", line 61, in <module>
    comm1 = Xgrad - rgradX
  File "C:\Users\fredb\AppData\Local\Programs\Python\Python38\lib\site-packages\galgebra\mv.py", line 2186, in __sub__   return Dop.Add(self, -dop)
  File "C:\Users\fredb\AppData\Local\Programs\Python\Python38\lib\site-packages\galgebra\mv.py", line 2135, in Add  raise ValueError('In Dop.Add complement flags have different values: %s vs. %s' % (dop1.cmpflg, dop2.cmpflg))
ValueError: In Dop.Add complement flags have different values: False vs. True
```
The attached zip file is a compilation of the results obtained with the different versions of Sympy.
I look forward to receiving any input on this.
Kind regards,
FB

[Issue with Sympy 1.3.zip](https://github.com/pygae/galgebra/files/3964848/Issue.with.Sympy.1.3.zip)

**Comment by eric-wieser** [comment]
> The following ValueError is returned at some point

We are already aware of this:

https://github.com/pygae/galgebra/blob/84ee81e49119fe1f46e4dc7262f5296d3aaec45c/doc/python/Dop.py#L31-L33

**Comment by eric-wieser** [comment]
Minimal repro of the other issue is:
```python
from sympy import symbols
from galgebra.ga import Ga
coords = x, y, z = symbols('x y z',real = True)
o3d, ex, ey, ez = Ga. build('e*x|y|z', g=[1, 1, 1] , coords=coords)
A = o3d.mv('A', 'vector', f=True)
lap = o3d.grad * o3d.grad
lap * A
```
which on my machine with sympy 1.6-dev, gives
```
Out[10]: (D{y}^2A__x + D{z}^2A__x)*e_x + (D{y}^2A__y + D{z}^2A__y)*e_y + (D{y}^2A__z + D{z}^2A__z)*e_z
```

**Comment by eric-wieser** [comment]
Mutable printing strikes again (xref gh-141). If you print `lap` before using it, then the bug doesn't occur. Will put out a PR to fix that first.

**Comment by eric-wieser** [comment]
Thanks for filing this, it's identified a large number of bugs in `Dop` and friends

**Comment by FreddyBaudine** [comment]
Dear Eric,
You’re welcome.  Pleased to have helped somewhat.
By the way, thank you for editing the title of the issue.
Regards,
Freddy

**Comment by eric-wieser** [comment]
Can you check if master, which contains gh-151, fixes your issue?

**Comment by eric-wieser** [comment]
Here's the pdf output when you code is run on master: [DotOperator_Simpy1.x.pdf](https://github.com/pygae/galgebra/files/3972792/DotOperator_Simpy1.x.pdf)

Does this look correct to you?

**Comment by FreddyBaudine** [comment]
Dear Eric,
Very many thanks for your help. It works !

I know you must be extremely busy but there is one issue (not fixed as yet) whose solution interests me most, and that is the instantiating of multi-linear functions (tensors) as described in Section 3.10 of Alan Brombrosky’s galgebra book, dated October 8, 2016.
The following error is returned when running TensorDef.py
“
Traceback (most recent call last):
  File "TensorDef.py", line 18, in <module>
    T = Mlt(TA,st4d) # Define multi-linear function
TypeError: __init__() missing 1 required positional argument: 'args'
 “
I understand that you’re aware of this bug and I was wondering when end users like me can hope for a fix or, at least, a workaround.

Kind Regards,
Freddy

**Comment by eric-wieser** [comment]
Unfortunately we have no working tests for `Mlt`, nor any real idea of what the tests should look like.

I'd encourage you to open a new issue about that, rather than continuing discussion here.
