### ISSUE TITLE
Regenerate notebooks using Sympy 1.5.0

### ISSUE THREAD

**Issue by eric-wieser** [pygae/galgebra#173]
Follow on from https://github.com/pygae/galgebra/pull/164#discussion_r359092136, it would be nice to have the notebook output as rendered by sympy 1.5.0, which in a few cases is more readable.

This should be as simple as:
* Installing sympy 1.5.0
* checking out the notebooks, running them in a clean kernel, and saving them again

**Comment by utensil** [comment]
Fixed by #209 .
