### ISSUE TITLE
Add pip release for Circle CI and remove Travis CI

### ISSUE THREAD

**Issue by utensil** [pygae/galgebra#174]
We're now mostly using the features and concurrency of Circle CI, so it's no longer worth it to maintain an obsolete TravisCI build.

The only thing we rely on Travis CI is the pip release, which can easily be ported to Circle CI. We should do it and remove Travis CI entirely.

**Comment by eric-wieser** [comment]
@utensil, this can be closed, right?

**Comment by utensil** [comment]
The pip release is added to Circle CI and removed from Travis CI. And Travis CI for PRs are disable, which is almost equivalent to being removed, will leave `.travis.yml` for a while without maintenance. Closing this issue.
