### ISSUE TITLE
Question on derivative / differential : why should coordinates be defined first ?

### ISSUE THREAD

**Issue by ying17zi** [pygae/galgebra#176]
Dear, 

Can we take the derivative of a function like the following without defining the coordinates?
Example function: $F(X) = |X|^k, 
and its derivative $\partial_X F(X) = k |X|^{k-2} \tilde{X}$.

(I'm a little confused after a first quick reading of the documentation.)

Thank you!

**Comment by eric-wieser** [comment]
This is somewhat possible, if involved, today, if you can construct an appropriate `Dop` instance.

However, the result will be expressed elementwise, so will give you the rather ugly (for a bivector X):
```
-X__xy*k*(X__xy**2 + X__xz**2 + X__yz**2)**(k/2 - 1)*e_x^e_y - X__xz*k*(X__xy**2 + X__xz**2 + X__yz**2)**(k/2 - 1)*e_x^e_z - X__yz*k*(X__xy**2 + X__xz**2 + X__yz**2)**(k/2 - 1)*e_y^e_z
```

**Comment by ying17zi** [comment]
> This is somewhat possible, if involved, today, if you can construct an appropriate `Dop` instance.
> 
> However, the result will be expressed elementwise, so will give you the rather ugly (for a bivector X):
> 
> ```
> -X__xy*k*(X__xy**2 + X__xz**2 + X__yz**2)**(k/2 - 1)*e_x^e_y - X__xz*k*(X__xy**2 + X__xz**2 + X__yz**2)**(k/2 - 1)*e_x^e_z - X__yz*k*(X__xy**2 + X__xz**2 + X__yz**2)**(k/2 - 1)*e_y^e_z
> ```

Would you mind elaborating a little on the construction of `Dop` in your above example?
Thank you very much!

**Comment by eric-wieser** [comment]
@ying17zi, unfortunately for that example I did not construct a `Dop` instance at all, I just typed in your algebraic result for the derivative to show you how `galgebra` will store it.

I think what's missing right now is that `galgebra` does not compute the reciprocal basis elements for all basis blades, only for the basis vectors. If it did, then what you ask for ought to be possible.

There's an extra complication in your example - you require `X` to be a blade, which also is not yet supported.

I suspect that @meuns has made some progress on one or both of these points in their fork.

**Comment by eric-wieser** [comment]
Here's how to construct such a dop (on master):
```python
import galgebra.mv
import galgebra.dop
import galgebra.metric

def make_mv_dop(g):
    r_basis = g.ReciprocalFrame(g.mv_basis, mode='norm')
    def r_blade(index):
        r_blade = g.mv(sympy.S(1), 'scalar')
        for i in index[::-1]:
            r_blade ^= -r_basis[i]
        return r_blade
    r_blades = g.indexes._map(lambda index: r_blade(index))
    blade_reciprocal_dict = {
        blade: r_blade
        for blade, r_blade in zip(g.blades.flat, r_blades.flat)
    }
    def mv_dop(x):
        terms = []
        for x_coef, blade in galgebra.metric.linear_expand_terms(x.obj):
            terms += [(blade_reciprocal_dict[blade], Pdop(x_coef))]
        return galgebra.mv.Dop(terms, ga=x.Ga)
    return mv_dop
```
used as:
```python
>>> mv_dop = make_mv_dop(my_algebra)
>>> dx = mv_dop(my_mv_x)
>>> dx  * f(x)
```

**Comment by ying17zi** [comment]
> This is somewhat possible, if involved, today, if you can construct an appropriate `Dop` instance.
> 
> However, the result will be expressed elementwise, so will give you the rather ugly (for a bivector X):
> 
> ```
> -X__xy*k*(X__xy**2 + X__xz**2 + X__yz**2)**(k/2 - 1)*e_x^e_y - X__xz*k*(X__xy**2 + X__xz**2 + X__yz**2)**(k/2 - 1)*e_x^e_z - X__yz*k*(X__xy**2 + X__xz**2 + X__yz**2)**(k/2 - 1)*e_y^e_z
> ```

Is it possible/difficult to achieve a non-element wise representation basing on this `dop`? :)
Thank you!

**Comment by eric-wieser** [comment]
No, but you can guess it's symbolic representation until you find one that's equal...

**Comment by eric-wieser** [comment]
In your particular example you can get most of the way there with `factor`:

```python
>>> (dX * F).obj.factor().simplify()
-k*(X__12**2 + X__13**2 + X__23**2)**(k/2 - 1)*(X__12*e_1^e_2 + X__13*e_1^e_3 + X__23*e_2^e_3)
```

Which by inspection is the result you require

**Comment by eric-wieser** [comment]
`.make_grad` supports this as of #326.

As for non-elementwise operations, that's tracked by another issue.
