### ISSUE TITLE
Set up Gitpod

### ISSUE THREAD

**Issue by utensil** [pygae/galgebra#20]
- [x] For upstream: 
[![](https://img.shields.io/badge/Run%20in%20Gitpod-brombo%2Fgalgebra-blue.svg?style=?style=flat&logo=codepen)](https://gitpod.io/#https://github.com/pygae/galgebra/tree/upstream_gitpod)
- [ ] For pygae/galgebra itself : 
[![](https://img.shields.io/badge/Run%20in%20Gitpod-pygae%2Fgalgebra-blue.svg?style=?style=flat&logo=codepen)](https://gitpod.io/#https://github.com/pygae/galgebra//tree/gitpod)
- [ ] Add https://probot.github.io/apps/gitpod/

The setup for upstream lies in https://github.com/pygae/galgebra/tree/upstream_gitpod .

The WIP setup for upstream lies in https://github.com/pygae/galgebra/tree/gitpod .

**Comment by eric-wieser** [comment]
Perhaps relevant: https://github.com/features/codespaces/?utm_source=announcement&utm_medium=blog&utm_campaign=satellite-product-recap

**Comment by utensil** [comment]
Yeah, I requested the early access.

I believe Gitpod might not be that necessary now and the preliminary setup is already there and no further work is needed. Closing this.
