### ISSUE TITLE
Set up proper release version system

### ISSUE THREAD

**Issue by utensil** [pygae/galgebra#21]
As discussed here: https://github.com/pygae/galgebra/pull/9#discussion_r262370967 , there should be a way to maintain the version number without redundancies.

Also we need to decide a release cycle, a few milestones and decide when can we send PRs to change sympy to point to pygae/galgebra as discussed here: https://github.com/brombo/galgebra/pull/42#issuecomment-464703367 as well as to change the wiki url: https://en.wikipedia.org/wiki/Geometric_algebra#Actively_developed_open_source_projects

P.S. I'm starting this issue to combine some potential lost discussions and to remove the TODO item from README.md to make it more user-friendly.

**Comment by utensil** [comment]
It would be awesome to use https://probot.github.io/apps/release-drafter/ and follow the convention in it so the release notes can be drafted if we properly maintain the titles and labels of PRs

**Comment by waldyrious** [comment]
Another option would be to use [python-semantic-release](https://github.com/relekang/python-semantic-release), which automatically determines a SemVer release type based on the messages of the commits included in it — and perhaps [semantic-pull-requests](https://github.com/probot/semantic-pull-requests) or some other tool to enforce commit messages following a given standard ([commitizen](http://commitizen.github.io/cz-cli/), [commitlint](https://github.com/conventional-changelog/commitlint)...).

Disclaimer: I haven't used these tools myself.

**Comment by utensil** [comment]
Yeah, I'm aware of __semantic release__ but I have some concerns about using these convention-enforcing tools. They impose the restrictions to the level of every commit (of contributors) to serve the need of release note drafter which is not friendly to new comers and it require setting up such commit message linters before commits which add more burdens to contributors and is time-consuming for PR reviewing process. Also the commit logs are immutable in nature compared to changeable PR titles and labels after the merge and before the release thus they don't serve the release note purpose very well.

All these concerns and given the immatural status of galgebra (compared to large community-driven open source projects), I will lean towards a more lightweight option such as the conventions in Release Drafter.

**Comment by waldyrious** [comment]
Fair points. 👍

**Comment by utensil** [comment]
Tried https://probot.github.io/apps/release-drafter/ on a test repo [here](https://github.com/utensil-test/experiments/releases), it looks like this:

![image](https://user-images.githubusercontent.com/64258/55322091-f2bc1a80-54ad-11e9-9e62-d91185ea1ab0.png)

**Comment by utensil** [comment]
I finally decide to use https://releases.readthedocs.io/ to maintain a [Changelog](https://galgebra.readthedocs.io/en/latest/changelog.html) manually as part of the source of GAlgebra for now because GAlgebra has not reached a point that would require such automatic mechanism and hand-written Changelog contains more details and is better organized.

So I'm closing this issue.

**Comment by eric-wieser** [comment]
Is there anything else to do here?

**Comment by utensil** [comment]
No, it's already done as https://releases.readthedocs.io/ is now very much alive a part of the maintenance of GAlgebra.
