### ISSUE TITLE
Codebeat does not understand python 3 code

### ISSUE THREAD

**Issue by eric-wieser** [pygae/galgebra#220]
See https://codebeat.co/projects/github-com-pygae-galgebra-master

Click on "namespaces", and search for "galgebra" - you'll see that many files are missing.

Perhaps this is a setting in the project config on codebeat somewhere, but I can't see that.

**Comment by utensil** [comment]
I looked around and have no idea what's going on. Should we consider drop Codebeat since we already have LGTM?

**Comment by eric-wieser** [comment]
Codebeat does a pretty good job at finding duplications and complexity, while LGTM is good at finding bugs - I've reached out to them to try and find out moree information

**Comment by eric-wieser** [comment]
I'm thinking we should migrate to https://codeclimate.com/github/pygae/galgebra instead

**Comment by utensil** [comment]
I'm OK with it, used it many years back.

In the meanwhile, `README.md` used [codacy](https://app.codacy.com/manual/utensilcandel/galgebra/dashboard) as its badge. I forgot why I chose it so it's back to a new free choice. I remember I added GAlgebra to a number of similar tools just to have a feeling about code quality issues (and did pretty much nothing about the alerts 😒 ). And `LGTM` and `flake8` have been utilized a lot by you.

I wonder what's the particular bit you like about Code Climate and why is it an equivalent (give or take) replacement for `Codebeat` and whether we plan to utilize it.

**Comment by eric-wieser** [comment]
Codebeat never responded, and at this point almost all of our files contain Python3-only syntax that makes codebeat ignore them. For that reason, I'm turning off their webhooks, if only to save energy.

**Comment by eric-wieser** [comment]
My memory of codacy was off, it looks like it's providing more useful tips than codeclimate after all.

I think we might want to configure it to ignore the `examples` directory.

**Comment by eric-wieser** [comment]
I now remember what my opposition to codacy was - it requests the `write:public_key` permission, which as far as I can tell essentially gives it total control over the commits in all my repositories.

**Comment by utensil** [comment]
Oh, then let's use CodeClimate.

**Comment by utensil** [comment]
> I now remember what my opposition to codacy was - it requests the `write:public_key` permission, which as far as I can tell essentially gives it total control over the commits in all my repositories.

I was trying to remove it but found it only in https://github.com/pygae/galgebra/settings/hooks and not requesting such permission.

**Comment by eric-wieser** [comment]
Sounds like you configured it before they changed their permission model. I'm happy to keep using it, I'm just not going to log in with my own GitHub account.

Have you looked at your personal "app" settings to see it's permissions there? (Or checked your ssh keys for an unwanted one)

**Comment by utensil** [comment]
Found permissions there and revoked them.

**Comment by utensil** [comment]
![image](https://user-images.githubusercontent.com/64258/83527949-126c2a00-a51b-11ea-9d93-e1086596a49c.png)

![image](https://user-images.githubusercontent.com/64258/83527972-1a2bce80-a51b-11ea-8fb1-bae4bdff0613.png)

This seems no accpetable by your standard. Will remove the codacy badge though I still find it informative: https://app.codacy.com/manual/utensilcandel/galgebra/dashboard

**Comment by eric-wieser** [comment]
> This seems not acceptable by your standard.

All of the organization options are acceptable to me. It's the user ones that aren't, but that's your problem not mine :)
