### ISSUE TITLE
Cherry-pick from forks of brombo/galgebra

### ISSUE THREAD

**Issue by utensil** [pygae/galgebra#24]
There're some nice work in other forks of brombo/galgebra, here's a summary:

Has some interesting changes:

- Python 3/Installation/misc fixes
  - https://github.com/godefv/galgebra
  - https://github.com/554richard/galgebra
  - ~~https://github.com/phlummox/galgebra~~ (superceded by `setup.py`)
- leo dorst book exercices
   - https://github.com/meuns/galgebra
  

No particular interesting changes:

- even
  - https://github.com/alexanderpokorny/galgebra
  - https://github.com/arivero/galgebra
  - https://github.com/atakan/galgebra
  - https://github.com/gabrielraya/galgebra
  - https://github.com/johanbluecreek/galgebra
  - https://github.com/mevangelista-alvarado/galgebra
  - https://github.com/NathanielBlairStahn/galgebra
  - https://github.com/prlw1/galgebra
  - https://github.com/rowhit/galgebra
  - https://github.com/skaslev/galgebra
  - https://github.com/vliviu/galgebra
  - https://github.com/vtrandal/galgebra
- diverged
  - https://github.com/arsenovic/galgebra : -8+5
  - https://github.com/ghtdak/galgebra: -39+1
- behind
  - https://github.com/lizhen-dlut/galgebra
  - https://github.com/lzfernandes/galgebra
  - https://github.com/njisrawi/galgebra
  - https://github.com/palazzol/galgebra
  - https://github.com/parsoyaarihant/galgebra
  - https://github.com/salotz/galgebra
  - https://github.com/sashmit/galgebra
  - https://github.com/satishgoda/galgebra
  - https://github.com/tormodv/galgebra

**Comment by eric-wieser** [comment]
Can we close this given #68 tracks the only remaining fork of interest?
