### ISSUE TITLE
Some tests are broken for SymPy 1.4

### ISSUE THREAD

**Issue by utensil** [pygae/galgebra#31]
SymPy 1.4 has just [released](https://github.com/sympy/sympy/wiki/release-notes-for-1.4) and some tests are broken for SymPy 1.4, see build https://circleci.com/workflow-run/dcbd3c98-45c3-4c89-abd6-2ea97fa07b2c .

Freeze SymPy version to 1.3 to keep CI green for now.

Tasks:

- [x] Fix broken `collect()` calls  ---- fixed by #48 
- [x] The fix for order change issue also needs to be delayed until the explicitly change to use SymPy 1.4 in CI after the collect() issue is addressed ---- fixed by #164 
- <del>adding a CI build for SymPy master so these issues can be detected sooner</del> tracked by #94

**Comment by utensil** [comment]
Errors are due to:

- `\quad` sometimes replaced by `\ `
- `\left(` sometimes replaced by `left (`, also for `\right` and `[{`
- some ordering has changed
- Raise exception when collecting a noncommutative symbol (sympy/sympy#15447 by @JMSS-Unknown)

**Comment by oscargus** [comment]
I'll see if I can update the printing tests for Galgebra correspondingly. (I did not find any instances of `\quad` in the tests files I found though.)

**Comment by utensil** [comment]
> I did not find any instances of `\quad` in the tests files I found though.

That's because we are using `nbval` to verify LaTeX or enhanced console output for galgebra by the Jupyter Notebooks in `examples/ipython`. It's an effective way to write tests for a symbolic library that has multiple output formats, but it's also sensitive to subtle changes between versions.

> I'll see if I can update the printing tests for Galgebra correspondingly.

Thanks!

The `\quad` and `\left` issue can be fixed by modifying https://github.com/pygae/galgebra/blob/15-print-pow/test/.nbval_sanitize.cfg to ignore this kind of differences.

The real difficulty is the `collect()` issue. Currently galgebra use `collect()` in quite some places to collect the bases of multivectors, probably should do it in another way, like manually collect the bases. It's correct for SymPy to raise exceptions if the symbols to be collected has no certain order in the expression, but in the case of the bases, they are always at the rightmost position so there's no confusion here.

The `collect()` issue must be fixed before way can change SymPy version in CI to 1.4. And It's non-trivial, so I'll not fix it in #17 but will fix it before 0.4.4 release.

The fix for order change issue(namely ) also needs to be delayed until the explicitly change to use SymPy 1.4 in CI after the `collect()` issue is addressed.


<blockquote><img src="https://avatars0.githubusercontent.com/u/33729520?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/pygae/galgebra">pygae/galgebra</a></strong></div><div>Symbolic Geometric Algebra/Calculus package for SymPy :crystal_ball: - pygae/galgebra</div></blockquote>

**Comment by asmeurer** [comment]
Once you get this fixed I would suggest adding a CI build for SymPy master so these issues can be detected sooner. We also plan to do a 1.5 release soon, so if you can test SymPy master now that would help.

**Comment by utensil** [comment]
Good idea, this was also brought up in https://github.com/sympy/sympy/issues/8365#issuecomment-61387644 and I forgot it.

Added to the task list in the main thread of this issue.

**Comment by utensil** [comment]
The task in this issue are done or tracked by separate issues, as reflected in the updated main thread. Closing.
