### ISSUE TITLE
Documentation edit links are broken

### ISSUE THREAD

**Issue by waldyrious** [pygae/galgebra#35]
For example, in https://galgebra.readthedocs.io/en/latest/galgebra_guide.html the edit link at the top right points to

    https://github.com/pygae/galgebra/blob/origin/master/doc/galgebra_guide.ipynb

...which yields a 404 error page. Instead, it should point to

    https://github.com/pygae/galgebra/blob/master/doc/galgebra_guide.ipynb

Note the extraneous `origin/` in the URL.

**Comment by utensil** [comment]
I've checked all configuration and have no idea where this extraneous `origin/` coming from. Any help will be appreciated.

**Comment by waldyrious** [comment]
Unfortunately I am not familiar with this setup, so I don't have any insight to offer. :(

Also, if I'm reading [your comment](https://github.com/pygae/galgebra/pull/36#issuecomment-535308957) correctly, that link should not even point to the `galgebra_guide.ipynb` file anyway, but the `galgebra.md` one instead — noting that here for reference.

**Comment by eric-wieser** [comment]
Fixed by toggling this box:

![image](https://user-images.githubusercontent.com/425260/82458523-ad421e80-9aae-11ea-88e1-f9a0ae5ce49e.png)


Looks like we were caught out by https://github.com/readthedocs/readthedocs.org/issues/5523

**Comment by utensil** [comment]
👍
