### ISSUE TITLE
Conversion of Printing to Python 3

### ISSUE THREAD

**Issue by ghost** [pygae/galgebra#38]
Thank you for picking up the torch with regard to galgebra.  I just did not have enough time to work on it as required.  I have a question about your conversion to python 3.  I am trying to use your version and it looks like the python 3 print function is not overloaded.  That is if A is a multivector or other object in galgebra the statement "print(A)" does not work.  Is this correct?

**Comment by utensil** [comment]
> Thank you for picking up the torch with regard to galgebra. I just did not have enough time to work on it as required.

So glad to see you again! How is everything going?

GAlgebra is a great piece of work and we are honored to do something about keeping it on.

> it looks like the python 3 print function is not overloaded. That is if A is a multivector or other object in galgebra the statement "print(A)" does not work. Is this correct?

It's overloaded and I verified the 4 ways of printing you designed.

First, printing plain texts. (I don't have an example at hand, will provide later)

Secondly, if called `Eprint()` upfront, `print()` will do Enhanced Console Printing(colored printing with ANSI escape sequences):

- code: https://github.com/pygae/galgebra/blob/master/examples/Terminal/terminal_check.py
- output: https://nbviewer.jupyter.org/github/pygae/galgebra/blob/master/examples/ipython/Terminal.ipynb

Thirdly, if called `Format()` in Jupyter Notebook upfront, `print()` will do LaTeX printing with MathJax.

- code & output: https://nbviewer.jupyter.org/github/pygae/galgebra/blob/master/examples/ipython/colored_christoffel_symbols.ipynb

Finally, if called `Format()` upfront and `xpdf()` eventually, `print()` will do LaTeX printing (internally, the standard output will be redirected to a buffer for later consumption):

- code: https://github.com/pygae/galgebra/blob/master/examples/LaTeX/colored_christoffel_symbols.py
- output: https://nbviewer.jupyter.org/github/pygae/galgebra/blob/master/examples/ipython/LaTeX.ipynb

**Comment by abrombo** [comment]
I took dop.ipynb from your ipython example and changed the line in cell 3 from "f" to "print(f)" and saved the executed and checkpoint ipynb file in dop.zip.  There were no errors generated and "print(f)" produced no output.  I used jupyterlab and was running python 3 as indicated by jupyterlab.

[dop.zip](https://github.com/pygae/galgebra/files/3676898/dop.zip)

Do you have any ideas as to what is happening?

**Comment by abrombo** [comment]
In looking at your code in printer for redirect and restore in GAlatexprinter I did not see the builtin print function redefined to overload it.  I also have worked on a python 3 version of galgebra.  Shown below is the critical code in the GALatexPrinter class for overloading the print function.  Any comments would be appreciated.  

    @staticmethod
    def redirect():
        GaLatexPrinter.latex_str = ''
        GaLatexPrinter.text_printer = print   #Save original print function
        builtins.print = printer.latex_print  #Redefine original print function
        GaLatexPrinter.latex_flg = True
        GaLatexPrinter.Basic__str__ = Basic.__str__
        GaLatexPrinter.Matrix__str__ = Matrix.__str__
        Basic.__str__ = lambda self: GaLatexPrinter().doprint(self)
        Matrix.__str__ = lambda self: GaLatexPrinter().doprint(self)

        return

    @staticmethod
    def restore():
        if GaLatexPrinter.latex_flg:
            builtins.print = GaLatexPrinter.text_printer  #Redefine orginal print function
            GaLatexPrinter.latex_flg = False
            Basic.__str__ = GaLatexPrinter.Basic__str__
            Matrix.__str__ = GaLatexPrinter.Matrix__str__
        return

**Comment by utensil** [comment]
I've just made a complete example for 4 ways to print in GAlgebra: https://nbviewer.jupyter.org/github/utensil/julia-playground/blob/master/py/printing-galgebra.ipynb

**Comment by utensil** [comment]
> I took dop.ipynb from your ipython example and changed the line in cell 3 from "f" to "print(f)" and saved the executed and checkpoint ipynb file in dop.zip. There were no errors generated and "print(f)" produced no output. I used jupyterlab and was running python 3 as indicated by jupyterlab.
> 
> [dop.zip](https://github.com/pygae/galgebra/files/3676898/dop.zip)
> 
> Do you have any ideas as to what is happening?

I consider this to be the expected behavior of your design. The code you listed above has the effect of redirecting standard output to a buffer object, so printing to standard output using `print()` will have no output as you had called `Format()` upfront. And if you do not call `Format()`, `print()` will work normally and output in the form of plain texts.

**Comment by abrombo** [comment]
I modified both printer.py and dop.ipynb in your python 3 distribution both are in 
[new_printer.zip](https://github.com/pygae/galgebra/files/3683750/new_printer.zip)
I ran dop.ipynb using the new printer and saved at checkpoint after executing.  This is the behavior I would want the print function to have in jupyter notebook/lab if "Format()" is called.  The reason is that it makes if easy to annotate an output cell as can be seen in dop.ipynb or to print multiple objects in one cell.  Also the code for outputting LaTeX is then the same in an pure python program or in a notebook using python.  What do you think?

**Comment by utensil** [comment]
Oh, that's what you mean by overloading the print function.

I'm currently out for vocation, but I'll evaluate and merge this ASAP.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by abrombo** [comment]
No rush.  My objective was to make printing seem as much as possible like python 3 printing.  Also, overloading the print function allows notebook printing to be the same as in normal (.py) python files.  In addition you can use multiple print function calls in a single notebook cell and print multiple objects in a notebook output cell.

**Comment by utensil** [comment]
This would be tracked in #39 .
