### ISSUE TITLE
Update the migration guide in README

### ISSUE THREAD

**Issue by utensil** [pygae/galgebra#394]
https://github.com/pygae/galgebra#migration-guide

- [x] mention that we now only support Python 3, and the last version that still supports Python 2.7
- [x] mention that API has changed a lot since the old version, many properties and methods are deprecated, see changelog
- [x] update the example `import`, remove the deprecated stuff

**Comment by eric-wieser** [comment]
Can probably add sympy 1.6 to that list too

**Comment by eric-wieser** [comment]
I assume you want to do this before releasing?

**Comment by eric-wieser** [comment]
Only one bullet point left here.

**Comment by utensil** [comment]
Fixed by #423
