### ISSUE TITLE
Use sphinx-math-dollar for Math formula in API documentation

### ISSUE THREAD

**Issue by utensil** [pygae/galgebra#43]
Just found `sphinx-math-dollar` from this post: https://www.asmeurer.com/blog/posts/quansight-labs-work-update-for-september-2019/ .

Currently, the API documentation of GAlgebra splits into two scattered pieces:

1. The old doc on the API converted from @abrombo 's original doc in LaTeX, it's great but it's somehow outdated (@abrombo has some updates on the doc and yet to be merged )
2. The API document automatically generated from docstrings in code but it's mostly ill-formated.

1 is at https://galgebra.readthedocs.io/en/latest/galgebra_guide.html#Module-Components
2 is at https://galgebra.readthedocs.io/en/latest/api.html .

The scenario causes maintenance burden and one of the reasons why @abrombo preferred to work on a separate repo is that it's difficult to maintain LaTeX doc and Sphinx doc (but there wasn't such an automatic API doc back then) at the same time.

By ill-formatted, I mean:

![image](https://user-images.githubusercontent.com/64258/66693112-eaa02b80-ecd7-11e9-948b-046c0155ef33.png)

It's still parseable but cumbersome. I was aware of this situation but I felt unwilling to rewrite them in the verbose syntax of reStructuredText so I left them there and treated them like plain text.

Now, with the help of `sphinx-math-dollar` which SymPy is also using, the situation can be fixed. So I opened this issue to add this work to the backlog.

However, this does not solve the maintenance burden issue which I only mentioned it as a context and comments and suggestions are welcome @abrombo @hugohadfield @eric-wieser .

**Comment by eric-wieser** [comment]
I'm not sure there's much point using `sphinx-math-dollar` - is there an objection to using ``` :math:`some_stuff` ``` (which the builtin sphinx.ext.mathjax provides) instead of `$ some_stuff $`?

**Comment by asmeurer** [comment]
If you use it let us know if you have any issues or feedback about it.

**Comment by utensil** [comment]
> I'm not sure there's much point using `sphinx-math-dollar` - is there an objection to using `` :math:`some_stuff` `` (which the builtin sphinx.ext.mathjax provides) instead of `$ some_stuff $`?

I think https://www.asmeurer.com/blog/posts/quansight-labs-work-update-for-september-2019/ is pretty self-explanatory.

And I personally don't wish to do the `` :math:`some_stuff` `` boilerplate work.

**Comment by eric-wieser** [comment]
I suppose either is fine - my point was that the dollar support is purely a convenience thing, and the latex rendering can be obtained with or without it. If the convenience is valuable, then by all means use it!

(Having said that, I just configured my editor to render :math: inline so am now biased)

**Comment by utensil** [comment]
This issue is no longer applicable since @eric-wieser used a different approach (i.e. use rst directly).

Specifically:

![image](https://user-images.githubusercontent.com/64258/83525835-1fd3e500-a518-11ea-9eb4-7b68d2e3bed5.png)

![image](https://user-images.githubusercontent.com/64258/83525856-25c9c600-a518-11ea-8919-740688a446dd.png)
