### ISSUE TITLE
Use sympy.core.compatibility for Py 2/3 issues

### ISSUE THREAD

**Issue by utensil** [pygae/galgebra#44]
When first converting GAlgebra from Python 2 to 3, I was not aware of [sympy.core.compatibility](https://github.com/sympy/sympy/blob/master/sympy/core/compatibility.py) and didn't wish to add a dependency like `six` so some compatibility issues are handled in `utils.py` which should actually be named `compat` or something but kept `utils` as its name so it may also used to put other utility functions.

So it's preferred to use `sympy.core.compatibility` to handle such issues in the future but the entry point could still be kept in `utils` if appropriate.

I do not worry that `sympy.core.compatibility` might go away one day, even this happens it will be after SymPy also drops support for Python 2.7 when past its EOL( https://pythonclock.org/ ), we can deal with the situation by cleaning up the remnants of python 2 support in a new release.

The background of this is that @abrombo 's new work on GAlgebra is no longer considering Python 2 support and I intend to keep the support for 2.7 for a while longer to consolidate its ground for the still-fresh Python 3 support.

**Comment by asmeurer** [comment]
The next SymPy release (1.5) will be the last to support Python 2.

**Comment by utensil** [comment]
I see, will keep the same pace.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eric-wieser** [comment]
I think this can be closed give we:
* Have dropped Python 2.7 support in master
* Have deprecated `galgebra.utils` which contained the 2.7 compatibility code.
