### ISSUE TITLE
Improvements (I hope) to the mv.py and lt.py modules

### ISSUE THREAD

**Issue by Greg1950** [pygae/galgebra#478]
I have made a number of changes to the **mv.py** and **lt.py** modules, changes which I believe address the issues about which I've previously posted.  I've improved the treatment of spinor-based orthogonal transformations so that now one can instantiate an orthogonal transformation using versors, a broader set of multivectors than are spinors.  And I've added to the multivector methods in **mv.py** several new methods, most of them inspired by Dorst, Fontijne, & Mann's *Geometric Algebra for Computer Science*. 

The changed modules have met every test I've made of them.  They are placed in the **galgebra** folder of the attached zip file.  Another folder, **notebooks**, contains four Jupyter notebooks.  Two of them describe precisely the changes I've made to the modules' code.  The other two are oriented towards GAlgebra users (as opposed to programmers).  A *Read Me First* file has been placed at the top level within the archive.

I'm much better at mathematics than programming.  My level of skill at the latter goes no further than a couple of introductory CS courses from M.I.T.'s edX division.  So I would appreciate it if readers of this GitHub issues forum, who are almost certainly better programmers than me, would look over the modified modules and test their functioning.  

(Changes in the indicated modules are delimited by comment lines `### GSG code starts ###` and `### GSG code ends ###`.  Those comment lines are there to aid real programmers in locating the modifications I've made.  They should be stripped out if it's decided by the PyGAE GAlgebra group that the modification should be kept.)

I can be contacted at g.s.grunberg@gmail.com.

Greg Grunberg

[GSG_2021-11-05_GAlgebra_fixes.zip](https://github.com/pygae/galgebra/files/7481560/GSG_2021-11-05_GAlgebra_fixes.zip)

**Comment by utensil** [comment]
x-ref: #475

**Comment by utensil** [comment]
Thank you, @Greg1950 , I believe this is covered by your improvements merged by #510 . Feel free to reopen if there are remaining issues.
