### ISSUE TITLE
Run tests on latest sympy

### ISSUE THREAD

**Issue by moble** [pygae/galgebra#489]
As mentioned [here](https://github.com/pygae/galgebra/pull/487#discussion_r1294152107) the tests currently run on sympy 1.7; as of this writing, the current sympy version is 1.12, and the tests fail on it.  When I removed the restriction to 1.7, I got [a lot of failures](https://github.com/moble/galgebra/actions/runs/5868440428/job/15911280790) that I'm guessing are related to sympy just organizing negative signs differently than it used to.  This means that explicit comparisons to old results (as are done with nbval and in test_test.py) can fail spuriously.  I suppose the thing to do would be to

  1. check more carefully than I have that most of those errors are indeed just sign-organization errors,
  2. re-run the notebooks to update their outputs, and
  3. update test_test.py to update its expected output.

**Comment by utensil** [comment]
Addressed by #493 .
