### ISSUE TITLE
Shirokov inverse?

### ISSUE THREAD

**Issue by spinjo** [pygae/galgebra#529]
Hi,

I want to do a symbolic calculation where I have to invert spacetime algebra multivectors that represent transformations, i.e. I use scalar, bivector and pseudoscalar grades only. The goal is to derive a generalization of the transformation [quaternion -> rotation matrix](https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation#Conversion_to_and_from_the_matrix_representation) for Lorentz transformations.

The `clifford` package can do it using the `.shirokov_inverse()` operation, however using `.inv()` (conventional implementations) does not work. The `galgebra` also struggles upon `u.inv()` because 'TypeError: `u * u.rev()` is not scalar'.

Is there a reason why the Shirokov Inverse is not implemented in `galgebra`? 
The [`clifford` implementation](https://github.com/pygae/clifford/blob/master/clifford/_layout.py#L574) does not look too crazy. I would be happy to give it a shot, if someone is confident that implementing this makes sense also for a symbolic tool like `galgebra`.

Cheers,
Jonas

Minimal working example `galgebra`:
```
import sympy
from galgebra.ga import Ga

ijkl = (i, j, k, l) = sympy.symbols("0 1 2 3", real=True)
algebra = Ga("e_0 e_1 e_2 e_3", g=[1,-1,-1,-1], coords=ijkl)
u = algebra.mv("uS", "scalar") + algebra.mv("uB", "bivector") + algebra.mv("uP", "pseudo")

print(u * u.rev()) # 'scalar + pseudoscalar' 
u.inv() # throws TypeError 'u*u.rev() is not a scalar'
```

Minimal working example `clifford`:
```
import clifford
import numpy as np
LAYOUT, BLADES = clifford.Cl(1, 3)

random = np.random.randn(8)
u = np.zeros(16)
u[0] = random[0]
u[5:11] = random[1:-1]
u[-1] = random[-1]
u = clifford.MultiVector(LAYOUT, value=u)
print(u* ~u) # 'scalar + pseudoscalar'
u.shirokov_inverse() # works
```

**Comment by EelcoHoogendoorn** [comment]
In dimensions < 6, the shirokov inverse isn't optimal. Something along the lines implemented here https://github.com/EelcoHoogendoorn/numga/blob/main/numga/multivector/extension/inverse.py

Is more performant and more numerically stable; I tend to call these 'hitzer inverses' but I don't know if that's accepted terminology.

**Comment by utensil** [comment]
Hi, @spinjo , I'm just back from vocation.

The implementation in `clifford` looks good to me, and there are more discussions in pygae/clifford#373 . PRs welcome!

There could a first PR to add it as `shirokov_inverse`, and the second PR could have more performance tests then decisde when to make it the default, for a symbolic package.

P.S. are you using the pip-version of GAlgebra, or the git version, or any variants?

**Comment by EelcoHoogendoorn** [comment]
I see that the link to the Clifford inverses has the hitzer ones implemented right below as well. Mine is a little more convoluted since it tries to find the inverse solution with the least number of geometric products given the terms actually present in the multivec, rather than picking the worst case for the given dimension. Also as implemented these hitzer inverses work for many mvs in dimensions beyond 5, just not for fully dense ones

**Comment by spinjo** [comment]
Thanks @utensil and @EelcoHoogendoorn for the context. I am mainly focused on getting my calculation done (in 4 dimensions). So I will implement it, see if the result makes sense, and open a PR once it works. 

I have been using the `pip` version for my tests.

**Comment by spinjo** [comment]
Thanks @utensil and @EelcoHoogendoorn for the context. I am mainly focused on getting my calculation done (in 4 dimensions). So I will implement it, see if the result makes sense, and open a PR once it works.

I have been using the `pip` version for my tests.

**Comment by spinjo** [comment]
The `clifford` package says something about how these methods relate in their [docs](https://clifford.readthedocs.io/en/latest/api/clifford.MultiVector.html?highlight=shirokov#clifford.MultiVector.inv): `inv()` tries
- `normalInv()` (I believe this is what `galgebra` has implemented)
- `hitzer_inverse()`
- `leftLaInv()`
They say that they don't use `shirokov_inverse()` because of numerical instabilities. @EelcoHoogendoorn is this related to what you say about dimension<6?

However their three implementations in `inv()` all don't work for my case, including the `hitzer_inverse()`. It seems that these methods make additional assumptions about the multivector that should be inverted. 
I am wondering if there is any theory behind which multivectors can be inverted and which can not. Is this a property of the specific geometric algebra (GA), i.e. spactime GA? Or maybe every GA has non-invertible multivectors?

**Comment by EelcoHoogendoorn** [comment]
> The `clifford` package says something about how these methods relate in their [docs](https://clifford.readthedocs.io/en/latest/api/clifford.MultiVector.html?highlight=shirokov#clifford.MultiVector.inv): `inv()` tries
> 
> * `normalInv()` (I believe this is what `galgebra` has implemented)
> * `hitzer_inverse()`
> * `leftLaInv()`
>   They say that they don't use `shirokov_inverse()` because of numerical instabilities. @EelcoHoogendoorn is this related to what you say about dimension<6?
> 
> However their three implementations in `inv()` all don't work for my case, including the `hitzer_inverse()`. It seems that these methods make additional assumptions about the multivector that should be inverted. I am wondering if there is any theory behind which multivectors can be inverted and which can not. Is this a property of the specific geometric algebra (GA), i.e. spactime GA? Or maybe every GA has non-invertible multivectors?

Well I suppose the numerics are not optimal in any dimension; but whats certain is that the hitzer solutions are both faster and more accurate. (and capable of returning only the relevant grades).

What numga implements I suppose you could call 'recursive hitzer inverses', whereas what clifford does is more a fused/single shot hitzer inverse. In my benchmarking the latter was significantly less performant. 

Inverses for all combinations of grades for all algebras < 6d are under unit test in numga; so the correct solution to your problem should be lurking there somewhere.

**Comment by EelcoHoogendoorn** [comment]
Note that your 4d versor has the same solution as the usual 4d versor. 

Multiply with its own reverse to get a study number; then you need a study number inverse; which you can get by multiplying the expression to be inverted by its non-scalar-negated self; so a 2 step hitzer inverse, id call it.

**Comment by utensil** [comment]
One choice of `inv()` is like how `norm()` is handling variants using a `hint` parameter. Because for a symbolic package, people tend to want the freedom to use the exact method they are exploring, and I personally wish to embrace all variants.

Another consideration is that the default implementation (without specifying the hint) should not have surprsingly worse performance. Implementation-wise, it would be nice to move the current implementation to a separate method, e.g. `normalInv()`, then call it from `inv()`, and when we figure out which method suits which scenario best, use branching to call different invert methods conditionally.

**Comment by koraxkorakos** [comment]
Ubsubscrine

26.12.2024 07:29:49 Utensil ***@***.***>:
