### ISSUE TITLE
Drop Python 2.7

### ISSUE THREAD

**Issue by eric-wieser** [pygae/galgebra#83]
Creating a tracking issue for this, not advocating we do it immediately

Since Python 2.7 is EOL on 2020-01-01, we could consider dropping support for python 2.7 on the same date, in line with https://python3statement.org/ (which notably includes SymPy).

Realistically, that would probably make 0.4.5 the last release to support python 2.

**Comment by utensil** [comment]
I'm now leaning towards make 0.4.5 the last version that supports Python 2.7.

Also, I would like to keep everything in 0.4.5 backwards-compatible and it could be released ASAP with only clean up PRs merged.

And the next release will be 0.5.0 which will drop Python 2.7 support and incorporate breaking changes like #63 and major features like #39 or # 19.
